test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  src:
    dsn: "root:123123@tcp(localhost:3306)/webook"
  dst:
    dsn: "root:123123@tcp(localhost:3306)/webook_intr"

kafka:
  addr:
    - "127.0.0.1:9094"

grpc:
  server:
    addr: ":8090"

#grpc:
#  addr: ":8090"

migrator:
  http:
    addr: ":8082"