test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  dsn: "root:123123@tcp(localhost:3306)/webook"

kafka:
  addr:
    - "localhost:9094"

grpc:
  server:
    addr: ":8090"

#grpc:
#  addr: ":8090"