test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  dsn: "root:123123@tcp(localhost:3306)/webook"

kafka:
  addr:
    - "127.0.0.1:9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      threshold: 100